apiVersion: v1
kind: Namespace
metadata:
  name: ems

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-deployment
  namespace: ems
  labels:
    app: ems
spec:
  selector:
    matchLabels:
      app: ems
  template:
    metadata:
      labels:
        app: ems
    spec:
      containers:
        - name: ems-server
          image: rajatgoyalfico/emp-org-chart:v2
          ports:
            - containerPort: 8086
          env:
            - name: MYSQL_USERNAME
              value: 'root'
            - name: MYSQL_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: 'ems'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_HOSTNAME
              value: 'mysql'
            - name: SERVER_PORT
              value: '8086'
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ems
spec:
  type: NodePort
  selector:
    app: ems
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8086
      
      